export default [
  {
    firstName: "John",
    lastName: "Doe",
    jobsCompleted: 342,
    rating: 4,
    estimatedPrice: 265,
    img: "https://api.time.com/wp-content/uploads/2017/12/terry-crews-person-of-year-2017-time-magazine-2.jpg",
  },
  {
    firstName: "Alice",
    lastName: "Smith",
    jobsCompleted: 123,
    rating: 5,
    estimatedPrice: 180,
    img: "https://www.instyle.com/thmb/vbLAcTd76IGlzcYTagRfllo3YTU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/062415-ariana-grande-lead-a98741bcafd64ca095099a3f77ce0639.jpeg",
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    jobsCompleted: 587,
    rating: 3,
    estimatedPrice: 412,
    img: "https://www.stargate-project.de/storage/app/media/charakterguide/stargate-atlantis-charakterguide-john-sheppard-joe-flanigan.jpg",
  },
  {
    firstName: "Emily",
    lastName: "Brown",
    jobsCompleted: 71,
    rating: 2,
    estimatedPrice: 98,
    img: "https://media.glamourmagazine.co.uk/photos/626c123bd9c995304913c7aa/4:3/w_1920,h_1440,c_limit/MILLIE%20BOBBY%20BROWN%20290422%20GettyImages-1181658863b.jpg",
  },
  {
    firstName: "Daniel",
    lastName: "Davis",
    jobsCompleted: 215,
    rating: 4,
    estimatedPrice: 325,
    img: "https://www.planetclaire.tv/wp-content/uploads/1999/06/stargate-sg1-oneill-season-3.jpg",
  },
  {
    firstName: "Olivia",
    lastName: "Miller",
    jobsCompleted: 659,
    rating: 5,
    estimatedPrice: 490,
    img: "https://m.media-amazon.com/images/M/MV5BODcwYTUwNzUtYzY1My00NGQ5LWJjOTItMjY4NmZkMWVlZWE0XkEyXkFqcGdeQXVyOTIzNjQ2NjY@._V1_.jpg",
  },
  {
    firstName: "David",
    lastName: "Wilson",
    jobsCompleted: 432,
    rating: 3,
    estimatedPrice: 198,
    img: "https://m.media-amazon.com/images/M/MV5BMTM4OTQ4NTU3NV5BMl5BanBnXkFtZTcwNjEwNDU0OQ@@._V1_.jpg",
  },
  {
    firstName: "Sophia",
    lastName: "Taylor",
    jobsCompleted: 89,
    rating: 4,
    estimatedPrice: 135,
    img: "https://i.pinimg.com/originals/91/dc/94/91dc9401800ed5102e2da86ddadc6322.jpg",
  },
  {
    firstName: "James",
    lastName: "Anderson",
    jobsCompleted: 524,
    rating: 5,
    estimatedPrice: 376,
    img: "https://m.media-amazon.com/images/M/MV5BNTczMzk1MjU1MV5BMl5BanBnXkFtZTcwNDk2MzAyMg@@._V1_FMjpg_UX1000_.jpg",
  },
  {
    firstName: "Emma",
    lastName: "Clark",
    jobsCompleted: 176,
    rating: 3,
    estimatedPrice: 288,
    img: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Julia_Gillard_2010.jpg",
  },
];
